version: "3.8"
services:
  code-server:
    image: lscr.io/linuxserver/code-server@sha256:c181b7a2ae59940f276c89fd86cd4f220cdb87886d771b5becf3d4156b3c0bc1
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password
      - DEFAULT_WORKSPACE=/config/workspace
      - PREFECT_API_URL=http://${VM_IP}:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    volumes:
      - ./code-server-config:/config
      - ${WORKSPACE_DIR}:/config/workspace
      - ./custom-init.sh:/custom-cont-init.d/setup.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8443:8443"
      - "4200:4200"
    restart: unless-stopped