[project]
name = "prefect_course_student"
version = "0.1.0"
description = "Prefect course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect-github>=0.3.0",
    "prefect>=3.0.11",
    "python-dotenv>=1.0.1",
    "scikit-learn>=1.5.2",
]